### ISSUE TITLE
No efl-dev on Ubuntu 22.10 (there is libefl-all-dev)

### ISSUE THREAD

**Issue by szabgab** [MaxPerl/Perl-Efl#2]
In README I saw that one needs to install `efl-dev` but on Ubuntu I only found `efl-doc` and `libefl-all-dev`. The latter worked as you can see in the PR #1

On Centos 7 I could not find the package needed.

**Comment by MaxPerl** [comment]
Thanks for the hint :-) I've corrected the Readme file. 

Your PR I will look at weekend (at the moment I don't understand well, what is the purpose of compiling / running tests on every push?)

Unfortunately not all distributions have efl/Enlightenment. But compiling the libraries is not a hard job... Perhaps the Budgie Desktop switch to efl, then the distribution coverage could be better...

Thank you so much for contributing!!!

Best wishes,
Max

**Comment by szabgab** [comment]
Thanks.

As this was part of my [Daily CI](https://dev.to/szabgab/the-2022-december-ci-challenge-5dof) project I am writing a blog post about this PR. I'll answer there as the answer could be interesting to the general public as well.
I'll post a link here when it is done.

**Comment by MaxPerl** [comment]
oh, very interesting!!! Thank you for this... I am very curious and looking forward to your blog post :-)

**Comment by szabgab** [comment]
[Here we are](https://dev.to/szabgab/adding-ci-to-perlefl-sometimes-you-need-to-do-some-extra-work-i1d).
